# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'GMBoxProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

pod 'AFNetworking'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDCycleScrollView'
pod 'SDAutoLayout'
pod 'Toast'
pod 'KSPhotoBrowser'
pod 'FORScrollViewEmptyAssistant'
pod 'Reachability'
pod 'JAnalytics'
end
